### PR TITLE
French translation + README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hello,
This PR adds the French translation and improve the README with a button to get the app. I can add the same button for google play but I guess your app is not on this store since I couldn't found it. If I'm wrong, just tell me ;)

You can ping me in the future if there are any new keys to translate.

Thanks for this app :)

### CODE REVIEW

**Comment by Bubu** [comment]
Thanks for the translations! I'm planning on making the about and rules section translatable: Right now they are [here](https://github.com/Bubu/android-dice-game/tree/master/app/src/main/res/raw).

Do you feel up to it?

I didn't make the app, I only dusted it off so that it doesn't disappear from F-droid.

As for the readme, I'd try to avoid mentioning 'Catan' all that much (copyright resasons). We should probably find a new name for this project and refer to Catan as a similar game. See also #3.

But I couldn't come up with any good ideas yet.

**Comment by Poussinou** [comment]
I will have a look on this other translations yep :+1: expect a new PR from me

For the name, we maybe can use something like **Katan** (looks like it was made by the KDE team, it's funny^^). It sounds the same, it's nearly the same spelling... Or **Catna**, **Tanca**, I don't know... But you're write, we have to avoid copyrights problems...

How could you recover the source code, out of curiosity?

**Comment by Bubu** [comment]
The files are not translatable yet I think, but I'll look into how to do that soon.

I kinda like Tanca, because it already sound like an Island. But maybe we'll find something better yet.

The code was here on github (see on the top, the forked from FatMonkeySmile/android-dice-game). I think this one was automatically migrated from google code, where the project lived before. I forked it because the build was broken and fdroid started moving all apps that couldn't be rebuild and still had an older md5 signature into the archive.

**Comment by Poussinou** [comment]
I translated the files in French, ping when you want me to push them, and specify the place where I have to do it, and the format of the file you need ;)

I prefer Katan, but Tanca is great also. Maybe you should rename the repository after that, since "android dice game" is not very appropriate. When I translated the file in French, I wasn't totally sure at the beginning it was the right game^^

Do you know others apps that were maybe removed from F-Droid? I could have a look at this, if I can find the source code somewhere on the internet...

**Comment by Bubu** [comment]
Thanks, I'll get back to you. But feel free to poke me again in a week or so, it sometimes help finding the time to work on this. :)

As for other disabled apps here is a forum post discussing the issue:
https://forum.f-droid.org/t/many-old-unmaintained-apps-have-been-archived/670/10

**Comment by Poussinou** [comment]
I will poke you with pleasure, since you ask me to do it :stuck_out_tongue: 

I will have a look at this, thanks :)

**Comment by Poussinou** [comment]
@Bubu From ping with love :stuck_out_tongue_winking_eye: 

But don't worry, we have time

**Pull request merged**
